### ISSUE TITLE
Host VDM on Terrascope

### ISSUE THREAD

**Issue by kvantricht** [WorldCereal/VDM#1]
@mbabic84 can you point me to the repository you're using for the VDM so we can attach issues to that repository?

**Comment by kvantricht** [comment]
As @mbabic84 asked by e-mail:

> After short inspection of system, there are some things I will probably need help with. Based on documentation, I should not try to update pre-installed packages, but we would like to update docker (and its components) to it's latest version ([https://docs.docker.com/engine/install/centos/](https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.docker.com%2Fengine%2Finstall%2Fcentos%2F&data=05%7C02%7C%7Cd2b5f156a631455da5a108dc1b341066%7C9e2777ed82374ab992782c144d6f6da3%7C0%7C0%7C638415157628325238%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=zOtX35F%2BYjnPzmuG%2FkUSFRaGwQbUO2Del2Na3xasqYI%3D&reserved=0)). Currently installed version has no "docker compose" command implemented yet. Next, VDM is usually listening on ports 80 a 443, but I am not able to access it from Internet right now. Is there a way how to enable this kind of access?

@jdries who from our side could follow up?

**Comment by kvantricht** [comment]
@mbabic84 I checked again internally and apparently the key colleague was ill at home for a couple of days. Normally today the credentials should be sent to you!

**Comment by kvantricht** [comment]
Update: VM is ready and credentials should have been provided to @mbabic84

**Comment by mbabic84** [comment]
All necessary files should be migrated to new VM. Everything seems to work without any issue. Could you, please, try to redirect domain to new IP to test if everything works as expected.

**Comment by kvantricht** [comment]
I passed this information on to our IT department. They just confirmed the change is made, but probably needs some time to be fully propagated. In case of further issues, you can e-mail Stijn (like before) as I'll be unavailable next week.
